import Fastify from "fastify";
import { describe, expect, it } from "vitest";
import { registerAdminUi } from "../src/api/admin-ui.js";

describe("admin UI", () => {
  it("serves the owner panel and theme assets", async () => {
    const app = Fastify();
    registerAdminUi(app);
    const page = await app.inject({ method: "GET", url: "/admin" });
    const styles = await app.inject({ method: "GET", url: "/admin/styles.css" });
    const script = await app.inject({ method: "GET", url: "/admin/app.js" });
    expect(page.statusCode).toBe(200);
    expect(page.headers["content-type"]).toContain("text/html");
    expect(page.body).toContain("Panel właściciela");
    expect(page.body).not.toContain("ADMIN_API_KEY=");
    expect(page.body).toContain("Kreator wdrożenia");
    expect(page.body).toContain("Widget pozostanie wyłączony");
    expect(page.body).toContain("Publikacja sklepu");
    expect(page.body).toContain("Kopie zapasowe");
    expect(page.body).toContain("Prywatność i retencja");
    expect(page.body).toContain("Eksport JSON");
    expect(page.body).toContain("Administratorzy");
    expect(page.body).toContain("Nazwa użytkownika");
    expect(page.body.indexOf('data-view-panel="privacy"')).toBeGreaterThan(page.body.indexOf("</aside>"));
    expect(page.body.indexOf('data-view-panel="privacy"')).toBeLessThan(page.body.indexOf("</main>"));
    expect(page.body).toContain('id="add-store-top"');
    expect(page.body).toContain("Porównania i podobieństwo");
    expect(page.body).toContain("Hasło administratora");
    expect(page.body).toContain("Jak ustawić podobieństwo?");
    expect(page.body).toContain("data-tooltip=");
    expect(page.body).toContain("Sugerowane pola");
    expect(page.body).toContain("Analizuj katalog");
    expect(page.body).toContain("Widget sklepu");
    expect(page.body).toContain("Otwórz podgląd");
    expect(page.body).toContain("Gotowy kod sklepu");
    expect(page.body).toContain("Historia rozmów");
    expect(page.body).toContain("Laboratorium jakości");
    expect(page.body).toContain("Quality &amp; Analytics");
    expect(page.body.match(/data-view="quality"/g)).toHaveLength(1);
    expect(page.body).not.toContain('data-view="conversations"');
    expect(page.body).not.toContain('data-view="usage"');
    expect(page.body).toContain("Kreator zakupowy");
    expect(page.body).toContain("Wykryj z katalogu");
    expect(page.body).toContain("Centrum synchronizacji");
    expect(page.body).toContain("Uruchom pełną synchronizację");
    expect(page.body).toContain("Harmonogram sklepu");
    expect(script.body).toContain("enqueueSync");
    expect(script.body).toContain("loadSyncJobs");
    expect(script.body).toContain("loadBackup");
    expect(script.body).toContain("loadPrivacy");
    expect(script.body).toContain("loadAdminUsers");
    expect(script.body).toContain("detectGuidedChoices");
    expect(script.body).toContain("runQuality");
    expect(script.body).toContain("quality-analytics?days=");
    expect(script.body).toContain("Rozmowy wymagające uwagi");
    expect(script.body).toContain("quality-scenarios/run-all");
    expect(script.body).toContain('options.body !== undefined ? { "Content-Type": "application/json" } : {}');
    expect(page.body).toContain("Słowa związane z produktami");
    expect(page.body).toContain('id="routing-continuation-terms"');
    expect(page.body).toContain('id="routing-restart-terms"');
    expect(script.body).toContain("data-topic-suggestions");
    expect(script.body).toContain("Pokaż wszystkie detale");
    expect(styles.body).toContain("--accent:");
    expect(styles.body).toContain('[data-theme="dark"]');
    expect(styles.body).toContain(".delete-button.confirming");
    expect(styles.body).toContain(".history-card");
    expect(styles.body).toContain("color-mix(in srgb,var(--accent) 35%");
    expect(styles.body).toContain(".sync-job-card");
    expect(styles.body).toContain(".backup-grid");
    expect(styles.body).toContain(".quality-overview-grid");
    await app.close();
  });
});
