const params=new URLSearchParams(location.search);const storeId=params.get("storeId")||"nortberg";const state={conversationId:null,conversationState:null,config:null,busy:false,selected:new Set(),lastRequest:null};
const $=(s)=>document.querySelector(s);const conversation=$("#conversation");const escapeHtml=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);

async function boot(){try{const response=await fetch(`/v1/widget/config?storeId=${encodeURIComponent(storeId)}`);if(!response.ok)throw new Error("Widget nie jest dostępny.");const body=await response.json();state.config=body.widget;applyConfig(body);renderWelcome();}catch(error){conversation.innerHTML=`<div class="error-card"><strong>Nie udało się uruchomić asystenta.</strong><br>${escapeHtml(error.message)}</div>`;disableComposer(true)}}
function applyConfig(body){const c=body.widget;$("#widget-title").textContent=c.title;$("#widget-subtitle").textContent=c.subtitle;$("#chat-input").placeholder=c.inputPlaceholder;$("#powered").hidden=!c.showPoweredBy;document.documentElement.dataset.theme=c.theme==="auto"?(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):c.theme;document.documentElement.style.setProperty("--brand",c.primaryColor);document.documentElement.style.setProperty("--brand-rgb",hexRgb(c.primaryColor));document.title=c.title}
function renderWelcome(){conversation.innerHTML=`<div class="welcome"><div class="message-row"><div class="mini-avatar">AI</div><div><div class="bubble">${escapeHtml(state.config.welcomeMessage)}</div><div class="message-meta">teraz</div></div></div><div class="starter-grid">${state.config.starterSuggestions.map(item=>`<button class="suggestion-button" data-message="${escapeHtml(item.message)}">${escapeHtml(item.label)}</button>`).join("")}</div></div>`;bindActions(conversation);scrollEnd()}
function addMessage(text,role="assistant"){const row=document.createElement("div");row.className=`message-row ${role}`;row.innerHTML=role==="user"?`<div><div class="bubble">${escapeHtml(text)}</div><div class="message-meta">teraz</div></div>`:`<div class="mini-avatar">AI</div><div><div class="bubble">${escapeHtml(text)}</div><div class="message-meta">teraz</div></div>`;conversation.append(row);scrollEnd()}
function showTyping(){const row=document.createElement("div");row.id="typing-row";row.className="message-row";row.innerHTML='<div class="mini-avatar">AI</div><div class="bubble typing"><span></span><span></span><span></span></div>';conversation.append(row);scrollEnd()}
async function send(payload,userLabel){if(state.busy)return;state.lastRequest={payload,userLabel};if(userLabel)addMessage(userLabel,"user");state.busy=true;disableComposer(true);showTyping();try{const response=await fetch("/v1/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeId,message:"",...(state.conversationId?{conversationId:state.conversationId}:{}),...(state.conversationState?{state:state.conversationState}:{}),...payload})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Nie udało się pobrać odpowiedzi.");state.conversationId=body.conversationId||state.conversationId;state.conversationState=body.state;renderResponse(body)}catch(error){$("#typing-row")?.remove();const card=document.createElement("div");card.className="error-card";card.innerHTML=`${escapeHtml(error.message)} <button class="suggestion-button" data-retry="true">Spróbuj ponownie</button>`;card.querySelector("button").addEventListener("click",()=>{card.remove();send(payload,"")});conversation.append(card);scrollEnd()}finally{state.busy=false;disableComposer(false);$("#chat-input").focus()}}
function renderResponse(body){$("#typing-row")?.remove();addMessage(body.message);if(body.products?.length)renderProducts(body.products);if(body.comparison)renderComparison(body.comparison);if(body.sources?.length)renderSources(body.sources);if(body.suggestions?.length){const wrap=document.createElement("div");wrap.className="suggestion-list";wrap.innerHTML=body.suggestions.map(item=>`<button class="suggestion-button" data-key="${escapeHtml(item.key)}" data-value="${escapeHtml(item.value)}">${escapeHtml(item.label)}</button>`).join("");conversation.append(wrap);bindActions(wrap)}scrollEnd()}
function renderProducts(products){const showCompare=products.length>1||state.selected.size>0;const wrap=document.createElement("div");wrap.className="product-strip";wrap.innerHTML=products.map(product=>`<article class="product-card">${product.similarityScore!=null?`<span class="similarity">${product.similarityScore}% zgodności</span>`:""}${showCompare?`<label class="compare-toggle"><input type="checkbox" data-product-id="${escapeHtml(product.externalId)}" ${state.selected.has(product.externalId)?"checked":""}> porównaj</label>`:""}<div class="product-image"><img src="${escapeHtml(safeUrl(product.imageUrl))}" alt="" loading="lazy"></div><div class="product-body"><a class="product-title" href="${escapeHtml(safeUrl(product.productUrl))}" target="_blank" rel="noopener noreferrer">${escapeHtml(product.title)}</a>${product.reasons?.length?`<div class="product-reasons">${product.reasons.slice(0,3).map(reason=>`<span>${escapeHtml(reason)}</span>`).join("")}</div>`:""}<div class="product-bottom"><span class="price">${formatPrice(product.price,product.currency)}</span><a class="product-link" href="${escapeHtml(safeUrl(product.productUrl))}" target="_blank" rel="noopener noreferrer">Zobacz</a></div></div></article>`).join("");conversation.append(wrap);wrap.querySelectorAll("img").forEach(image=>image.addEventListener("error",()=>image.closest(".product-image")?.remove()));wrap.querySelectorAll("[data-product-id]").forEach(input=>input.addEventListener("change",()=>toggleProduct(input)))}
function renderComparison(comparison){const names=new Map(comparison.products.map((p,i)=>[p.externalId,`Produkt ${i+1}`]));const card=document.createElement("div");card.className="comparison-card";card.innerHTML=`<div class="comparison-title">Porównanie produktów</div><div class="comparison-scroll"><table class="comparison-table"><thead><tr><th>Parametr</th>${comparison.products.map(p=>`<th>${escapeHtml(names.get(p.externalId))}</th>`).join("")}</tr></thead><tbody>${comparison.fields.map(field=>`<tr><td>${escapeHtml(field.label)}</td>${field.values.map(value=>`<td class="${field.bestProductIds.includes(value.externalId)?"best":""}">${escapeHtml(value.display)}${field.bestProductIds.includes(value.externalId)?" ✓":""}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;conversation.append(card)}
function renderSources(sources){const el=document.createElement("div");el.className="source-list";el.innerHTML=`Źródła: ${sources.map(source=>`<a href="${escapeHtml(safeUrl(source.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(source.title)}</a>`).join(" · ")}`;conversation.append(el)}
function consumeSuggestions(){conversation.querySelectorAll(".suggestion-list,.starter-grid").forEach(element=>element.remove())}
function bindActions(root){root.querySelectorAll("[data-message]").forEach(button=>button.addEventListener("click",()=>{consumeSuggestions();send({message:button.dataset.message},button.textContent)}));root.querySelectorAll("[data-key]").forEach(button=>button.addEventListener("click",()=>{const value=button.dataset.value;consumeSuggestions();if(["similar","similarCheaper"].includes(button.dataset.key)){state.selected.clear();state.selected.add(value);updateComparisonBar()}send({selection:{key:button.dataset.key,value:/^-?\d+(?:\.\d+)?$/.test(value)?Number(value):value}},button.textContent)}))}
function toggleProduct(input){if(input.checked){if(state.selected.size>=3){input.checked=false;return}state.selected.add(input.dataset.productId)}else state.selected.delete(input.dataset.productId);updateComparisonBar()}
function updateComparisonBar(){const count=state.selected.size;$("#comparison-bar").hidden=count===0;$("#comparison-count").textContent=`${count} ${count===1?"wybrany":count<5?"wybrane":"wybranych"}`;$("#compare-selected").disabled=count<2}
function clearSelection(){state.selected.clear();document.querySelectorAll("[data-product-id]").forEach(input=>input.checked=false);updateComparisonBar()}
function disableComposer(disabled){$("#chat-input").disabled=disabled;$("#send-button").disabled=disabled}
function scrollEnd(){requestAnimationFrame(()=>conversation.scrollTo({top:conversation.scrollHeight,behavior:"smooth"}))}function formatPrice(value,currency){return new Intl.NumberFormat("pl-PL",{style:"currency",currency}).format(value)}function hexRgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)).join(",")}function safeUrl(value){try{const url=new URL(value,location.origin);return ["http:","https:"].includes(url.protocol)?url.href:"#"}catch{return"#"}}
$("#chat-form").addEventListener("submit",event=>{event.preventDefault();const input=$("#chat-input"),message=input.value.trim();if(!message)return;consumeSuggestions();input.value="";input.style.height="auto";send({message},message)});$("#chat-input").addEventListener("input",event=>{event.target.style.height="auto";event.target.style.height=`${Math.min(event.target.scrollHeight,110)}px`});$("#chat-input").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();$("#chat-form").requestSubmit()}});$("#compare-selected").addEventListener("click",()=>{if(state.selected.size>=2){consumeSuggestions();send({action:{type:"compare",productIds:[...state.selected]}},`Porównaj ${state.selected.size} wybrane produkty`)}});$("#clear-selection").addEventListener("click",clearSelection);$("#reset-chat").addEventListener("click",()=>{state.conversationId=null;state.conversationState=null;clearSelection();renderWelcome()});boot();
