import { and, count, eq, gte, sql, sum } from "drizzle-orm";
import type { Database } from "../db/client.js";
import { aiUsageEvents, runtimeHeartbeats } from "../db/schema.js";

export type AiLimitConfig = { enabled:boolean;requestsPerMinute:number;dailyRequests:number;monthlyTokens:number;maximumMessageCharacters:number;alertPercent:number;inputCostUsdPerMillionTokens:number;outputCostUsdPerMillionTokens:number;limitMessage:string };
export const defaultAiLimits:AiLimitConfig={enabled:true,requestsPerMinute:30,dailyRequests:2000,monthlyTokens:2_000_000,maximumMessageCharacters:4000,alertPercent:80,inputCostUsdPerMillionTokens:0,outputCostUsdPerMillionTokens:0,limitMessage:"Asystent osiągnął chwilowy limit. Spróbuj ponownie za moment."};
export type UsageDenial="minute_requests"|"daily_requests"|"monthly_tokens";
const day=(now:Date)=>new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));
const month=(now:Date)=>new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));
const numeric=(row:Record<string,unknown>|undefined)=>Object.fromEntries(Object.entries(row??{}).map(([key,value])=>[key,Number(value??0)]));

export class AiUsageRepository {
  constructor(private readonly db:Database){}
  async reserve(input:{storeId:string;requestId:string;kind:string;model:string;limits:AiLimitConfig;now?:Date}):Promise<{allowed:true;eventId:string}|{allowed:false;reason:UsageDenial}>{const now=input.now??new Date();return this.db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`ai:${input.storeId}`}))`);if(input.limits.enabled){const[minute]=await tx.select({value:count()}).from(aiUsageEvents).where(and(eq(aiUsageEvents.storeId,input.storeId),gte(aiUsageEvents.createdAt,new Date(now.getTime()-60_000))));if(Number(minute?.value??0)>=input.limits.requestsPerMinute)return{allowed:false as const,reason:"minute_requests" as const};const[daily]=await tx.select({value:count()}).from(aiUsageEvents).where(and(eq(aiUsageEvents.storeId,input.storeId),gte(aiUsageEvents.createdAt,day(now))));if(Number(daily?.value??0)>=input.limits.dailyRequests)return{allowed:false as const,reason:"daily_requests" as const};const[monthly]=await tx.select({value:sql<number>`coalesce(sum(${aiUsageEvents.inputTokens}+${aiUsageEvents.outputTokens}),0)`}).from(aiUsageEvents).where(and(eq(aiUsageEvents.storeId,input.storeId),gte(aiUsageEvents.createdAt,month(now))));if(Number(monthly?.value??0)>=input.limits.monthlyTokens)return{allowed:false as const,reason:"monthly_tokens" as const};}const[event]=await tx.insert(aiUsageEvents).values({storeId:input.storeId,requestId:input.requestId,kind:input.kind,model:input.model}).returning({id:aiUsageEvents.id});if(!event)throw new Error("Could not reserve AI usage");return{allowed:true as const,eventId:event.id};});}
  async complete(id:string,input:{inputTokens:number;outputTokens:number;latencyMs:number;limits:AiLimitConfig}){const cost=Math.round(input.inputTokens*input.limits.inputCostUsdPerMillionTokens+input.outputTokens*input.limits.outputCostUsdPerMillionTokens);await this.db.update(aiUsageEvents).set({status:"completed",inputTokens:input.inputTokens,outputTokens:input.outputTokens,estimatedCostMicrousd:cost,latencyMs:input.latencyMs,completedAt:new Date()}).where(eq(aiUsageEvents.id,id));}
  async fail(id:string,errorCode:string,latencyMs:number){await this.db.update(aiUsageEvents).set({status:"failed",errorCode:errorCode.slice(0,80),latencyMs,completedAt:new Date()}).where(eq(aiUsageEvents.id,id));}
  async summary(storeId:string,now=new Date()){const[dayRow]=await this.db.select({requests:count(),inputTokens:sum(aiUsageEvents.inputTokens),outputTokens:sum(aiUsageEvents.outputTokens),costMicrousd:sum(aiUsageEvents.estimatedCostMicrousd),failures:sql<number>`count(*) filter (where ${aiUsageEvents.status}='failed')`,averageLatencyMs:sql<number>`coalesce(avg(${aiUsageEvents.latencyMs}) filter (where ${aiUsageEvents.latencyMs} is not null),0)`}).from(aiUsageEvents).where(and(eq(aiUsageEvents.storeId,storeId),gte(aiUsageEvents.createdAt,day(now))));const[monthRow]=await this.db.select({requests:count(),inputTokens:sum(aiUsageEvents.inputTokens),outputTokens:sum(aiUsageEvents.outputTokens),costMicrousd:sum(aiUsageEvents.estimatedCostMicrousd)}).from(aiUsageEvents).where(and(eq(aiUsageEvents.storeId,storeId),gte(aiUsageEvents.createdAt,month(now))));return{day:numeric(dayRow),month:numeric(monthRow)};}
}

export class RuntimeRepository {constructor(private readonly db:Database){}async heartbeat(component:string,instanceId:string,metadata:Record<string,unknown>={}){await this.db.insert(runtimeHeartbeats).values({component,instanceId,metadata}).onConflictDoUpdate({target:runtimeHeartbeats.component,set:{instanceId,metadata,heartbeatAt:new Date()}});}async status(){return this.db.select().from(runtimeHeartbeats);}}
