import { z } from "zod";
import * as cheerio from "cheerio";
import { storeConfigSchema, type StoreConfig } from "../config/store.js";
import { fetchGoogleMerchantFeed } from "../importers/google-merchant.js";
import { extractTechnicalRows } from "../scrapers/product-page.js";
import { fetchPublicResource } from "../security/public-url.js";

export const onboardingStoreSchema=z.object({id:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(2).max(50),name:z.string().min(2).max(100),feedUrl:z.url(),locale:z.string().min(2).max(20).default("pl-PL"),productPage:z.object({enabled:z.boolean().default(false),specificationRowSelector:z.string().min(1).max(300).default("table tr")}),knowledgeSources:z.array(z.object({type:z.enum(["html","pdf"]),topic:z.string().regex(/^[a-z0-9_-]+$/).min(2),url:z.url()})).max(30).default([]),startImport:z.boolean().default(true)});
export type OnboardingStoreInput=z.infer<typeof onboardingStoreSchema>;

export async function analyzeFeed(url:string){const products=await fetchGoogleMerchantFeed(url);if(!products.length)throw new Error("Feed does not contain products");const present=(key:"brand"|"category"|"size"|"gtin")=>products.filter(item=>Boolean(item[key])).length;return{productCount:products.length,currencies:[...new Set(products.map(item=>item.currency))],availability:[...new Set(products.map(item=>item.availability))].slice(0,20),coverage:{brand:present("brand"),category:present("category"),size:present("size"),gtin:present("gtin"),description:products.filter(item=>item.descriptionHtml.length>0).length,image:products.filter(item=>item.imageUrl.length>0).length},productHosts:[...new Set(products.map(item=>new URL(item.productUrl).hostname))],samples:products.slice(0,5).map(item=>({externalId:item.externalId,title:item.title,price:item.price,currency:item.currency,availability:item.availability,productUrl:item.productUrl,imageUrl:item.imageUrl,brand:item.brand,category:item.category}))};}

export async function analyzeProductPage(url:string){const response=await fetchPublicResource(url,{headers:{"user-agent":"ShopAgentOnboarding/0.1"},maximumBytes:5_000_000}),html=await response.text();const selectors=["#tab2 table tr",".woocommerce-Tabs-panel table tr","[role=tabpanel] table tr",".tab-content table tr","table tr"];const candidates=selectors.map(selector=>({selector,rows:extractTechnicalRows(html,selector)})).filter(item=>item.rows.length>0).sort((a,b)=>b.rows.length-a.rows.length);const $=cheerio.load(html);return{title:$("title").text().trim(),candidates:candidates.map(item=>({selector:item.selector,rowCount:item.rows.length,sample:item.rows.slice(0,6)})).slice(0,5)};}

export function buildStoreConfig(input:OnboardingStoreInput):StoreConfig{const polish=input.locale.toLowerCase().startsWith("pl");return storeConfigSchema.parse({schemaVersion:1,id:input.id,name:input.name,feed:{type:"google_xml",url:input.feedUrl},productPage:input.productPage,knowledgeRetrieval:{locale:input.locale,stopWords:[],topicAliases:Object.fromEntries(input.knowledgeSources.map(source=>[source.topic,[source.topic]])),topicSuggestions:{},insufficientEvidenceRules:[]},conversationRouting:{productTerms:polish?["produkt","szukam","potrzebuję","cena","porównaj"]:["product","looking","need","price","compare"],contactTerms:polish?["oddzwoń","skontaktujcie się ze mną"]:["call me","contact me"],continuationTerms:polish?["a jak","a gdzie","a kiedy","a ile","a czy","co z"]:["and how","and where","when","how long","what about"],restartProductTerms:polish?["od nowa","zacznij od nowa","nowe wyszukiwanie"]:["start over","new search"],contactResponse:polish?"Skorzystaj proszę z oficjalnego kanału kontaktowego sklepu.":"Please use the store's official contact channel.",unknownResponse:polish?"Napisz proszę, czy szukasz produktu, czy informacji o sklepie.":"Please tell me whether you need a product or store information."},answerGeneration:{enabled:true,tone:"friendly"},aiLimits:{enabled:true,requestsPerMinute:30,dailyRequests:2000,monthlyTokens:2_000_000,maximumMessageCharacters:4000,alertPercent:80,inputCostUsdPerMillionTokens:0,outputCostUsdPerMillionTokens:0,limitMessage:polish?"Asystent osiągnął chwilowy limit. Spróbuj ponownie za moment.":"The assistant has reached a temporary limit. Please try again shortly."},syncSchedule:{enabled:false,intervalHours:24},privacy:{conversationHistoryEnabled:true,conversationRetentionDays:90,allowAdminExport:true},publicationRequirements:{minimumProducts:1,minimumEnrichmentPercent:80,requireKnowledgeSources:true,minimumQualityScenarios:3,requireAllQualityPassing:true},widget:{enabled:false,title:polish?`Asystent ${input.name}`:`${input.name} Assistant`,subtitle:polish?"Pomogę wybrać odpowiedni produkt":"I will help you choose the right product",welcomeMessage:polish?"Dzień dobry! Czego szukasz?":"Hello! What are you looking for?",inputPlaceholder:polish?"Napisz, czego szukasz…":"Tell me what you need…",primaryColor:"#2563eb",theme:"auto",showPoweredBy:true,starterSuggestions:[]},productComparison:{fields:[{id:"price",label:polish?"Cena":"Price",source:{type:"commercial",key:"price"},format:"currency",preference:"min"}],similarityWeights:{price:1},similarityRules:{price:{required:false,minimumSimilarity:0,mismatchPenalty:0}},minimumScore:0},knowledgeSources:input.knowledgeSources});}
